language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm test
before_deploy:
  - npm run build
deploy:
  edge: true
  provider: npm
  email: "$NPM_EMAIL_ADDRESS"
  api_key: "$NPM_API_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    branch: master